# Generated by Django 4.1.4 on 2022-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_me_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
